# Set the value of the SPOKE_REPOSITORIES secret to a newline-delimited list of repositories you want to receive ref updates.
# Note that manifest.lkml will only be updated if this line is present in the file: #automatically_track_head: yes

# Example value for SPOKE_REPOSITORIES (don't include the preceding # characters):
# git@github.com:drewgillson/my_fruit_basket.git
# git@github.com:drewgillson/your_fruit_basket.git

name: Update Remote Dependency Ref in Spoke Projects

on:
  push:
    branches:    
    - 'master'  

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set remote dependency ref value in spoke projects to the most recent commit SHA in this hub project
      run: |
        mkdir ~/.ssh
        cat <<EOT | tee -a ~/.ssh/${{ secrets.KEY_NAME }}
        ${{ secrets.PRIVATE_KEY }}
        EOT
        chmod 600 ~/.ssh/${{ secrets.KEY_NAME }}
        cat <<EOT | tee -a ~/.ssh/${{ secrets.KEY_NAME }}.pub
        ${{ secrets.PUBLIC_KEY }}
        EOT
        chmod 644 ~/.ssh/${{ secrets.KEY_NAME }}.pub
        eval "$(ssh-agent -s)"
        ssh-add
        git config --global user.email "action@github.com"
        git config --global user.name "${{ github.actor }} via GitHub Actions"
        echo "${{ secrets.SPOKE_REPOSITORIES }}" | while read row
        do
          dir=`echo $row | sed 's/.\{4\}$//' | sed 's/.*\///'`
          mkdir /home/runner/$dir
          cd /home/runner/$dir
          git clone $row .
          if grep -q "automatically_track_hub: yes" "manifest.lkml"; then
            sed -i -E 's/ref: "(.*)"/ref: "${{ github.sha }}"/g' manifest.lkml
            git add manifest.lkml
            git commit -m "ci: Automatically set remote_dependency ref to most recent commit" -a | exit 0
            git push -u origin master
          else
            echo "$dir/manifest.lkml is not configured to automatically track the hub"
            exit 1
          fi
        done
