name: Update Manifest Import Reference

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update manifest project import reference to HEAD ref of base project
      continue-on-error: true
      run: |
        mkdir ~/.ssh
        cat <<EOT | tee -a ~/.ssh/${{ secrets.KEY_NAME }}
        ${{ secrets.PRIVATE_KEY }}
        EOT
        chmod 600 ~/.ssh/${{ secrets.KEY_NAME }}
        cat <<EOT | tee -a ~/.ssh/${{ secrets.KEY_NAME }}.pub
        ${{ secrets.PUBLIC_KEY }}
        EOT
        chmod 644 ~/.ssh/${{ secrets.KEY_NAME }}.pub
        eval "$(ssh-agent -s)"
        ssh-add
        git config --global user.email "action@github.com"
        git config --global user.name "${{ github.actor }} via GitHub Actions"
        echo "${{ secrets.SPOKE_REPOS }}" | while read row
        do
          dir=`echo $row | sed 's/.\{4\}$//' | sed 's/.*\///'`
          mkdir /home/runner/$dir
          cd /home/runner/$dir
          echo "Attempting to clone $row"
          git clone $row .
          if grep -q "automatically_track_head: yes" "manifest.lkml"; then
            pwd
            cat manifest.lkml
            sed -i -E 's/ref: "(.*)"/ref: "${{ github.sha }}"/g' manifest.lkml
            git add manifest.lkml
            git commit -m "ci: Automatically set remote_dependency ref to newest commit" -a | exit 0
            git push -u origin master
          fi
        done
