name: Update Manifest Import Reference

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update manifest project import reference to HEAD ref of base project
      run: |
        mkdir ~/.ssh
        cat <<EOT | tee -a ~/.ssh/${{ secrets.KEY_NAME }}
        ${{ secrets.PRIVATE_KEY }}
        EOT
        chmod 600 ~/.ssh/${{ secrets.KEY_NAME }}
        cat <<EOT | tee -a ~/.ssh/${{ secrets.KEY_NAME }}.pub
        ${{ secrets.PUBLIC_KEY }}
        EOT
        chmod 644 ~/.ssh/${{ secrets.KEY_NAME }}.pub
        eval "$(ssh-agent -s)"
        ssh-add
        git config --global user.email "action@github.com"
        git config --global user.name "${{ github.actor }} via GitHub Actions"
        echo "${{ secrets.SPOKE_REPOS }}" | jq
        #echo '${{ secrets.SPOKE_REPOS }}' | jq -r '.[] | .repo' | while read row
        #do
        #  dir=`echo $row | sed 's/.\{4\}$//' | sed 's/.*\///'`
        #  mkdir $dir
        #  cd $dir
        #  git $row .
        #  sed -i -E 's/ref: "(.*)"/ref: "${{ github.sha }}"/g' manifest.lkml
        #  git add manifest.lkml
        #  git commit -m "ci: Automatically updated ref" -a | exit 0
        #  git push -u origin master
        #done
