name: Update Manifest Import Reference

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update manifest project import reference to HEAD ref of base project
      run: |
        cat <<EOT | tee -a key
        ${{ secrets.PRIVATE_KEY }}
        EOT
        chmod 600 key
        eval "$(ssh-agent -s)"
        ssh-add key
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        mkdir my-fruit-basket
        cd my-fruit-basket
        git clone git@github.com:drewgillson/my_fruit_basket.git .
        echo "#${{ github.ref }}" >> manifest.lkml
        git add manifest.lkml
        git commit -m "ci: Automated build push" -a | exit 0
        git push -u origin master
